evershop:
  database:

    # datasource, must by one of [sqlite, mysql]
    datasource: sqlite
    mysql:
      hostname: 127.0.0.1
      username: test
      password: test
      db_name: test
      prefix: es_
      port: 3306
    sqlite: 
      filename: database.db
      prefix: es_

  # use this material to link chests and create shops
  linkMaterial: redstone

  # use this material to destroy shop signs in creative mode
  destroyMaterial: golden_axe
  
  # the maximum number of chests/redstone components that a single shop can connect with
  maxLinkBlocks: 100

  # Default language
  #   Shop items will *always* be displayed using the player's client language settings.
  #   Transaction messages will be displayed with the same language of client only if the language is supported. Or
  #   the default language will be used. You can add your own translations to plugin/EverShop/i18n folder, following 
  #   the same pattern with en_us.yml, and it will be loaded automatically when the plugin starts.
  default_translation: en_us

  # Shop type alias
  #   You can add shop type alias here. The left-most matching phrase will be used as the shop type. (case insensitive)
  alias:
    BUY: [出售, 卖]
    SELL: 收购

  # hooks
  worldguard:
    # configure whether players can link chests/components in regions.
    #  - none : player can link everything
    #  - flag : player can only link blocks in regions that he can access chests and redstone components
    #  - member : player can only link blocks in regions which he is a member/owner of
    restrict_link: member
  
  lockettepro:
    # configure whether players can link locked chests
    #  - none : player can link everything
    #  - user : user of the lock (everyone that can access the chest) can link
    #  - owner : only the owner of the lock can link
    #  - all : only unlocked chest can be linked
    restrict_link: user

  # TODO - tax logic
  tax:
    consumption_tax:
      type: by_transaction_progressive # none, static, by_balance, by_transaction_static, by_transaction_progressive
      tiers: 
        "0": 0.01
        "10": 0.02
        "20": 0.03
        "50": 0.04
        "100": 0.06
        "500": 0.08
        "1000": 0.1
    income_tax:
      type: by_balance
      tiers:
        "0": 0
        "100": 0.01
        "1000": 0.02
        "2000": 0.03
        "5000": 0.04
        "10000": 0.05
        "20000": 0.07
        "50000": 0.1